@url = http://localhost:3000


#profile controller
### Get all profiles
GET {{url}}/profiles

### Get a profile by search
GET {{url}}/profiles/search?name=John

### Get a profile by ID
GET {{url}}/profiles/1

### Create a new profile
POST {{url}}/profiles
Content-Type: application/json

{
   "firstName": "John",
    "lastName": "Doe",
    "email": "johndoe@example.com",
    "role": "patient",
    "phoneNumber": "0712345678"
}

### Update a profile by ID
PATCH {{url}}/profiles/2
Content-Type: application/json

{
  "profileId": 1,
  "firstName": "John Smith",
  "email": "updatejohn.doe@example.com"
}

### Delete a profile by ID
DELETE {{url}}/profiles/3

#patient controller

### Get all patients
GET {{url}}/patient

### Get a patient by ID
GET {{url}}/patient/1

### Create a new patient
POST {{url}}/patient
Content-Type: application/json

{
    "dateOfAdmission": "2023-10-01",
    "dateOfDischarge": "2023-10-10",
    "dateOfBirth": "1990-01-01",
    "address": "Nairobi",
    "city": "Nairobi",
    "profileId": 1
}


### Delete a patient by ID
DELETE {{url}}/patient/1


### get doctors
GET {{url}}/doctor
### Create a new doctor
POST {{url}}/doctor
Content-Type: application/json

{
    "firstName": "Benard",
    "lastName": "Steven",
    "email": "benard.steven@example.com",
    "phoneNumber": "0712345657",
    "specialty": "Cardiology",
    "yearsOfExperience": 2,
    "password": "securepassword",
    "status": true
}

### Get a doctor by ID
GET {{url}}/doctor/2
### Update a doctor by ID
PATCH {{url}}/doctor/2
Content-Type: application/json

{
    "firstName": "Benard",
    "lastName": "Steven",
    "email": "benard.steven@example.com",
    "phoneNumber": "0712345657",
    "specialty": "Cardiology",
    "yearsOfExperience": 5,
    "password": "securepassword",
    "status": true
}
