@url = http://localhost:3000
@AccessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImVtYWlsIjoiZGF2aWRtYWluYUBleGFtcGxlLmNvbSIsInJvbGUiOiJkb2N0b3IiLCJpYXQiOjE3NDk0NzI1OTEsImV4cCI6MTc0OTQ3MzQ5MX0.34DhRPVZkZFyaLfVE8IH9EeGXb4Yweo0QI9nBkTxefM
@RefreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImVtYWlsIjoiZGF2aWRtYWluYUBleGFtcGxlLmNvbSIsInJvbGUiOiJkb2N0b3IiLCJpYXQiOjE3NDk0NzI1OTEsImV4cCI6MTc1MDA3NzM5MX0.lVyTVGxA0LGqj7HbPHZxQIr1dNiIeDKATxfftHzOMIk
## Authentication
### Register a new user
POST {{url}}/profiles
Content-Type: application/json

{
  "firstName": "david",
  "lastName": "maina",
  "email": "davidmaina@example.com",
  "password": "password003",
  "role": "doctor"
}

### Login a user
POST {{url}}/auth/signin
Content-Type: application/json

{
  "email": "davidmaina@example.com",
  "password": "password003"
}

### Get all profiles
GET {{url}}/profiles
Authorization: Bearer {{AccessToken}}


### signout
GET {{url}}/auth/signout/1


### seed data
POST {{url}}/seed

#profile controller
### Get all profiles
GET {{url}}/profiles

### Get a profile by search
GET {{url}}/profiles/search?name=John

### Get a profile by ID
GET {{url}}/profiles/1

### Update a profile by ID
PATCH {{url}}/profiles/2
Content-Type: application/json

{
  "profileId": 1,
  "firstName": "John Smith",
  "email": "updatejohn.doe@example.com"
}

### Delete a profile by ID
DELETE {{url}}/profiles/3

#patient controller

### Get all patients
GET {{url}}/patient

### Get a patient by ID
GET {{url}}/patient/1

### Create a new patient
POST {{url}}/patient
Content-Type: application/json

{
    "dateOfAdmission": "2023-10-01",
    "dateOfDischarge": "2023-10-10",
    "dateOfBirth": "1991-11-04",
    "address": "Nairobi",
    "city": "Nairobi",
    "profileId": 2
}


### Delete a patient by ID
DELETE {{url}}/patient/3


### get doctors
GET {{url}}/doctor
### Create a new doctor
POST {{url}}/doctor
Content-Type: application/json

{
    "firstName": "Benard",
    "lastName": "Steven",
    "email": "benard.steven@example.com",
    "phoneNumber": "0712345657",
    "specialty": "Cardiology",
    "yearsOfExperience": 2,
    "password": "securepassword",
    "status": true
}

### Get a doctor by ID
GET {{url}}/doctor/2
### Update a doctor by ID
PATCH {{url}}/doctor/2
Content-Type: application/json

{
    "firstName": "Benard",
    "lastName": "Steven",
    "email": "benard.steven@example.com",
    "phoneNumber": "0712345657",
    "specialty": "Cardiology",
    "yearsOfExperience": 5,
    "password": "securepassword",
    "status": true
}



