version: '3.8'

services:
  wegHospital:
    image: postgres:15-alpine
    container_name: wegHospital_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PSWD: postgres
      POSTGRES_DB: wegHospital
    ports:
      - "5432:5432"
    volumes:
      - wegHospital_db_data:/var/lib/postgresql/data
    networks:
      - app-network
  redis:
    image: redis:8.0-alpine
    container_name: wegHospital_redis_cache
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "{REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - wegHospital_redis_data:/data
    networks:
      - app-network
